development:
  charset_type: zh_cn.utf-8
  bin_path: /usr/local/coreseek/bin
  charset_dictpath: /usr/local/mmseg3/etc
  ngram_len: 0

  searchd_file_path: /web/sphinx

  charset_table: "0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F"

  wordforms: /web/sphinx/wordforms.txt
  exceptions: /web/sphinx/exceptions.txt
  stopwords: /web/sphinx/stopwords.txt
